### ISSUE TITLE
QUESTION is there a Vue 3 version planned?

### ISSUE THREAD

**Issue by dheimoz** [ledermann/blurhash-vue#1]
Hello @ledermann , hope you are doing awesome.
I was looking at your fantastic job with this component. I wonder if you are planning a vue 3 version. Otherwise I would like to know if you are accepting PR's? I can work on it next week. 

Thanks.

**Comment by ledermann** [comment]
No, I'm not planing a Vue 3 version. This repo is more of a one-time example, not a long-term supported project. 
But if you want to update the example to Vue 3, I would be happy to accept a PR.

**Comment by dheimoz** [comment]
Awesome, thanks @ledermann .
